var flavourList = ['Piss','Piss 2','Peepee','Shid','Bug Nut','Bug Jazz ','Century Egg','Birch Beer','Cocaine','Chinchilla Jerky','Bull Penis','Ambiguous Apple','Rock','Tissue','Molten Copper','Ant Larvae','Tarantula Trimmings','Insect Sex Hormones ','Pig Eye Fluid ','New Banana Flavour ','Laundry Detergent ','Enzymes ','Anglerfish Foetus  ','The Number 24™','Human Blood ','Dust','Lemon ','Straight Alcohol','Gay Alcohol ','Lesbian Alcohol','Spiked Piss','Chloroform','Grape','Raspberry','Blackberry','Strawberry','Blueberry','Citron','Orange','Passion fruit ','Pomegranate','Dragonfruit ','Grapefruit ','Holly','Mandarin ','Tangerine','Fabric of Spacetime','Slavery','Olive','Watermelon','Cactus','Chocolate','Vanilla','Chemicals','Uranium 235 Fuel Rods','Nuclear Waste','ATP ','Mitochondria ','Yogurt ','Greek Mythology ','Mermaids','Sesame Street ','Linen','Vladimir Lenin ','Plastic','Rubber','Broken Glass','Asphalt','Wood Tar','Granite Countertop','General Electric Refrigerator ','Razor','Drywall','Cheese','Pepper','Pepperoni' ,'Deluxe Pizza ','Spinach','Bomb','The Pentagon ','A Pentagon','Area 51 ','Someone&#39;s Mother','Sadness ','Ceiling Tile','Piss 3 ','Binary Encoding ','Mid Century Typography','At Least 10 pixels ','Found Footage  ','Entrails ','The Screams of Pigs in the Slaughterhouse ','Lasers','Doorknobs ','Elytras ','Antennae ','GIFs ','GIFs','Crusty JPEG ','Sonic Gfuel ','Walmart   ','The Equinox ','TI-84 Plus CE Calculator ','Hernan Cortez ','The Letter 3 ','Hours Wasted Playing Ranked Shooter Games ','Agony (Girliepop Edition) ','Stats and Trigonometry Homework ','Escape Key ','Macbook ','Radicals ','Aluminium Slag ','Boo Berry and Sonic Gfuel ','Pinot Grigio de Sicilia ','British Healthcare  ','September 8th 2022 15&#58;10 BST ','Whiteboard Eraser Residue ','Review ','Twosday ','Earwax ','The Fake Wood the School&#39;s Tables are Made Out of ','The &quot;Safe space for all&quot; sign ','Paint ','Mechanical Pencil','Tardigrade ','Tree ','Piss 4 ','rG&#58;GrºwG','Japanese Typographic Ink Slab','Hercules Beetle ','Graphite ','Fried Chicken','Pollo Frito ','XXL Hot Italian Sausage Pizza ','Obesity ','Anaemia ','Nutrient Deficiency ','Foetus ','The &quot;U&quot; in Colour and Favourite ','𓅂 ','The Half-full Starbucks Cup Left in the Target Toilet Paper Isle ','Every Geometric Shape Except for a Pentagon ','Every Government Building Except for the Pentagon ','Problem 12 ','The Gogol from Albanian Mythology ','Kepler-452b ','Spacial Vacuum',
'Warm Water','Grime from People&#39;s Keyboards','Light with a Wavelength of 420&#46;69 Nanometers ','Airplay ','Yum Yum Sauce','The Concept of Something Breaking ','The Sound of Ice in a Dunkin Donuts Cup ','Mild Discomfort ','Cream Cheese ','Bag of Aluminium Cans ','Hall Pass ','Banana Fritter Batter ','Egg','Maroon Dry Erase Marker ','Male Insect Gamete ','Leather  ','Computer Science Principles Textbook ','H  ','A Series of Unfortunate Events&#58; The Show ','Stranger Things Pre-Season 4 ','Breaking Bad ','Heavy Breathing ','Unorganised Wires','Organised Wires ','A Prime Flavour Unknown to Science ','Powerpoint ','Pre-2010&#39;s Internet ','George Washington Fighting at Saratoga ','Four Segment IP Address ','Teenage Mutant Ninja Turtles','Crystal Lake ','Envelope Lick Action Sealant ','Шаилушай','Grandfather Must','The Liquid Produced by the Quirky Animatronics At Night','Rot','Flan','Rice Pudding','Rice Pudding with Cinnamon ','Tapioca Pudding','Pudding Deez Nuts','Deez Nuts Feastables ','Dog Served with Rice','Fugu (with the Poison Parts)','Defence Against the Dark Arts','Yellow Highlighter Fluid ','Nucleus','Dimensional Analysis Practice Problems','Balls Swinging Like a Grandfather Clock ','The Essence of a Cat&#39;s Soul ','Halitosis ','Scoliosis ','Cake ','Brain Tumour with All The Fixings ','Cornbread ','Arizona Green Tea ','Sonic Energy Drink ','Sour Smurfs','Scalp ','Dried Scalp','Seaweed ','Salmon Roe ','Onigiri (Wasabi Tuna) ','Jelly Donut ','Fingernail Creating Cells ','32 Day Old Copper ','Fresh Pokémon Card Smell ','Intel CPU Sticker','Intel CPU ','Stun Seed ','Anger of a Dumped Boyfriend ','Scorn','Rancour ','Solid Mercury ','Solid Bromine','Soy Sauce ','90&#39;s Urban Japan ','Rotating Cranium','Migraine ','How to Basic','Deaths Caused by Wikihow ','Mickey and Friends Parking Structure ','Thomas Jefferson ','Transcendentalism  ','Electronegativity of Lead ','Sticky Note','Junkyard Smell ','Meter Stick, But Only the Parts that Aren&#39;t Labelled ','William Dafoe ','Paper Cut ','New Car Smell','Children Working in the Factory ','iPhone 302&#46;6 ','The Singular Avocado Slice in the iPhone 15 ','Vegan People ','Mechanical Clock ','Quartz Clock ','Electricity ','200 Calories of Water ','The Joy of Running with Scissors  ','Diarrhoea of a Wimpy Kid','Diarrhoea of the Mouth ','Slumber Cucumber ','Sleeping  ','Excretion','Fancy Words for Farting','Cheddar Cheese','Brie Cheese','Gouda Cheese',
'Parmesan Cheese','Pecorino Cheese','Mozzarella Cheese','Swiss Cheese ','Queso Blanco Cheese','Asiago Cheese','Blue Cheese','Bocconcini Cheese','Burrata Cheese','Camembert Cheese','Colby Cheese','Cotija Cheese','Cottage Cheese','Cream Cheese ','Ricotta Cheese','Feta Cheese','Gorgonzola Cheese','Quark Cheese Cheese','Danish Blue Cheese','Grana Padano Cheese','Stilton Cheese','Appenzeller Cheese','Roquefort Cheese','Raclette Cheese','Cement','Brick','Spaghetti','Javascript (EN)','Javascript (JA)','Javascript (ES)','Javascript (IT)','Javascript (FR)','Javascript (BS) ','Farm Fresh™ Butt Nuggets™  ','Mango Salsa ','Rotten Onions ','Putrid Pastry ','Water ','Prohibition ','Gummy Bear','Civil Disobedience ','Organised Crime','Analog Horror ','Anniversary','Birthday Cake','Tax Evasion ','The Sound of a Hydroflask Dropping ','Dilly-dallying ','Sentience','Lack of Sentience ','Withering ','Time','Space','Death','Creation ','Mexican-American War ','3D Emoji GIFS','3D Emoji GIFS ','Sunflower ','Mr&#46; Breast Fuckables™ ','Mr&#46; Beast Feastables™ ','Lemon 2  ','Grimace&#39;s Nutsack ','Logan Paul Liquid ','KSI Fluid ','Purple','Ourple ','Stray Hair in the Mouth ','Gum Foil ','Aluminium Foil ','Tungsten Foil ','Slacking ','Osmosis ','Quotes from the Jungle Book ','Grass ','Shitpost Status Thumbnails','Sugar','Honey ','Molasses ','Vegemite ','Peanut Butter (XXXXtra Crunchee) ','Ocean Flora','Chlorophyll ','Japanese Bathing Sponge','Rusty metal','Locker room ','Sternum ','Pelvic Thrust','The Abyss ','Arctic Freeze','Bubblegum ','Plum','Newspaper','Communist Propaganda ','The Last 4 Minutes of School ','Artificial Intelligence','The Singularity ','Tooth Powder','Bubblegum Deep-Cleaning Toothpaste ','Dentist Tooth Glue ','Steve Jobs ','Amazon Box','Magnets','Bootleg ','Fresh Canadian Snow  ','Cat Dander','Glass','Sea Glass ','Demon Core','Sea Salt ','Screwdriver ','Eldritch Horror  ','Nordic Countries ','Calendar','Lust ','Opening a Soda for the First Time ','Yellow Snow ','Fizzy-Faz ','Early 2020&#39;s Mascot Horror ','Sourcerer ','Tlatoani ','Basket ','Monitor Lizard ','3031 ','Poorly Built Ikea Table ','Period of Silence After a Test ','Dark Green ','Wrath Towards the Tubby Girlfriend ','Piss 5','Piss Infused with Hibiscus Tea ','Holiday Piss','Spooky Piss ','Saint Patrick&#39;s Day Piss ','Lovely Piss','Summer Piss ','Back-To-School Piss ','Thankful Piss ','Uncle Sam&#39;s Toe Jam','Patriotic Piss ','Inclusive Piss ','Tragic Piss ','Earth Piss '
,'Getting-Work-Off Day Piss','Haii &#58;333 piss ','Allergens ','Pansexual Alcohol ','Asexual Alcohol ','Bisexual Alcohol','Straight But Proud Alcohol','Dreamsexual Alcohol','Spectrasexual Alcohol ','Androsexual Alcohol ','Autosexual Alcohol ','Demisexual Alcohol ','Gynosexual Alcohol','Anger of a Misidentified Italian ','Skoliosexual Alcohol','Polysexual Alcohol'];

var btn = document.querySelector("flavourWheel");
    var out = document.getElementById("flavourOutput");
    
  
    btn.addEventListener("click", getWord);

    output("cum");
   
    function getWord(){
     
      
      
      var wordNum = Math.floor(Math.random() * flavourList.length);
      
     
      output.textContent = flavourList[wordNum];
    }